apiVersion: v1
kind: Pod
metadata:
  namespace: kube-example
  name: nginx-pod
spec:
  shareProcessNamespace: true
  containers:
  - name: nginx
    image: nginx
  - name: shell
    image: busybox
    stdin: true
    tty: true
