apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment # Name of our deployment
  namespace: kube-example
  labels:
    app: nginx
spec:
  replicas: 5      # number of pods
  selector:        # this is how deployment knows what pod to manage
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx   # define pod label
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2     # Image version
        ports:
        - containerPort: 80
